apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: require-resources-limits
  annotations:
    policies.kyverno.io/description: Каждый контейнер должен иметь лимиты по памяти и загрузке cpu через requests.memory\cpu и limits.memory
spec:
  variables:
    - name: containers
      expression: >-
        object.spec.containers + (has(object.spec.initContainers) ? object.spec.initContainers : [])
  validationActions: [Deny]
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [pods]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: [kube-system, kube-public, kube-node-lease, kyverno, monitoring, local-path-storage, cnpg-system]
  validations:
    - expression: >-
        variables.containers.all(c, has(c.resources) && has(c.resources.requests) && has(c.resources.requests.cpu) && has(c.resources.requests.memory) && has(c.resources.limits) && has(c.resources.limits.memory))
      message: "Необходимо установить лимиты по памяти на контейнер"
  autogen:
    podControllers:
      controllers: [deployments, statefulsets, daemonsets, jobs, cronjobs]
