FROM golang:1.22 As build

WORKDIR /app

COPY api/go.mod ./
COPY api/main.go ./

RUN CGO_ENABLED=0 go build -o /out/api .

FROM scratch
COPY --from=build /out/api /api

EXPOSE 8080

ENTRYPOINT ["/api"]
